language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get install -qq --force-yes libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-net-dev libphysfs-dev libglew-dev cppcheck
script: cmake . && make
after_script: cppcheck --verbose --enable=all --std=posix --std=c++11 --quiet `git ls-files source/\*.cpp`
notifications:
  irc:
    channels:
      - "chat.freenode.net#physhexgames"
    on_success: always
    on_failure: always
    template:
      - "Commit : %{commit_message}"
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
