language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update && sudo apt-get upgrade
  - yes | sudo add-apt-repository -y 'deb http://ftp.us.debian.org/debian/ testing main'
  - yes | sudo add-apt-repository -y 'deb http://us.archive.ubuntu.com/ubuntu/ xenial main'
  - sudo apt-get install debian-archive-keyring
  - sudo apt-get clean && sudo apt-get update -qq
  - sudo apt-get install -qq --force-yes cppcheck
  - sudo apt-get install -qq --force-yes libglew-dev
  - sudo apt-get install -qq --force-yes libphysfs-dev
  - sudo apt-get install -qq --force-yes libsdl2-dev
  - sudo apt-get install -qq --force-yes libsdl2-image-dev
  - sudo apt-get install -qq --force-yes libsdl2-mixer-dev
  - sudo apt-get install -qq --force-yes libsdl2-ttf-dev
  - sudo apt-get install -qq --force-yes libsdl2-net-dev
script: cmake . && make
after_script: cppcheck --verbose --enable=all --std=posix --std=c++11 --quiet `git ls-files source/\*.cpp`
notifications:
  irc:
    channels:
      - "chat.freenode.net#physhexgames"
    on_success: always
    on_failure: always
    template:
      - "Commit : %{commit_message}"
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
